"""initial metadata schema

Revision ID: a942647ea402
Revises: 
Create Date: 2026-07-16 22:58:37.944047
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a942647ea402'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('filename_nfc', sa.Text(), nullable=False),
    sa.Column('filename_casefold', sa.Text(), nullable=False),
    sa.Column('natural_sort_key', sa.LargeBinary(), nullable=False),
    sa.Column('device', sa.Integer(), nullable=False),
    sa.Column('inode', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('modified_ns', sa.Integer(), nullable=False),
    sa.Column('content_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('waiting_stable', 'analyzing', 'ready', 'retry_wait', 'failed', 'no_valid_content', name='analysisstatus'), nullable=False),
    sa.Column('cover_status', sa.Enum('not_generated', 'queued', 'generating', 'complete', 'generation_failed', name='coverstatus'), nullable=False),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_casefold', sa.Text(), nullable=False),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('creator_raw', sa.Text(), nullable=True),
    sa.Column('circle', sa.Text(), nullable=True),
    sa.Column('translated', sa.Boolean(), nullable=True),
    sa.Column('parser_version', sa.Integer(), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=False),
    sa.Column('field_confidence_json', sa.Text(), nullable=False),
    sa.Column('parse_warnings_json', sa.Text(), nullable=False),
    sa.Column('unclassified_tags_json', sa.Text(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_filename_casefold'), ['filename_casefold'], unique=False)
        batch_op.create_index('ix_files_identity', ['device', 'inode', 'size'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_title_casefold'), ['title_casefold'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('checked_entries', sa.Integer(), nullable=False),
    sa.Column('changes_found', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_casefold', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'value')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_value_casefold'), ['value_casefold'], unique=False)

    op.create_table('web_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_sessions_expires_at'), ['expires_at'], unique=False)

    op.create_table('cache_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('content_version', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    with op.batch_alter_table('cache_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cache_entries_kind'), ['kind'], unique=False)

    op.create_table('file_tags',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'tag_id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('entry_name', sa.Text(), nullable=False),
    sa.Column('uncompressed_size', sa.Integer(), nullable=False),
    sa.Column('crc32', sa.Integer(), nullable=False),
    sa.Column('unavailable', sa.Boolean(), nullable=False),
    sa.Column('unavailable_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'page_number')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_file_id'), ['file_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_task_type'), ['task_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))

    op.drop_table('tasks')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_file_id'))

    op.drop_table('pages')
    op.drop_table('file_tags')
    with op.batch_alter_table('cache_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cache_entries_kind'))

    op.drop_table('cache_entries')
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_sessions_expires_at'))

    op.drop_table('web_sessions')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_value_casefold'))

    op.drop_table('tags')
    op.drop_table('scans')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_title_casefold'))
        batch_op.drop_index(batch_op.f('ix_files_status'))
        batch_op.drop_index('ix_files_identity')
        batch_op.drop_index(batch_op.f('ix_files_filename_casefold'))

    op.drop_table('files')
    # ### end Alembic commands ###
